name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Set Versions
        uses: actions/github-script@v5
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: mvn -f framework/pom.xml --batch-mode deploy -Drevision=${{ steps.set_version.outputs.no-v }} -Dchangelist=-${{ github.run_attempt }} -Dsha1=
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
